import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { getServerAuthSession } from "~/server/auth";
import { TRPCReactProvider } from "~/trpc/react";
import Provider from "./context/Provider";
import NavBar from "./_components/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  dialogs: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" data-theme="night">
      <body className={`font-sans ${inter.variable}`}>
        <Provider session = {session}>
        <TRPCReactProvider cookies={cookies().toString()}>
        <NavBar />
          {props.children}
          {props.dialogs}
        </TRPCReactProvider>
        </Provider>
      </body>
    </html>
  );
}
